---
title: "simulating_data.rmd"
output: html_document
date: "2026-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse)
```

## R Markdown


#setup kalman filter agent


```{r}
aliens <- expand_grid(
  a = 0:1,
  b = 0:1,
  c = 0:1,
  d = 0:1,
  e = 0:1
) %>% 
  mutate(danger = b)


```




Single position kalman update
```{r}
mu0 = 1
sigma0 = 1

#def single kalman update, given previous mean, previous uncertainty in mu (a vector of coordinates), observation and assumend noise in enviroment, and process noise (drift in latent state). Note that sigma, obs_noise and process_noise are given in SDs. 
kalman_update <- function(mu_prev, sigma_prev, obs, obs_noise, process_noise){
  
  #pred location. Not necessary, since its a static target model, ie no predictable movement assumed between measurements. 
  mu_pred <- mu_prev
  
  #pred sigma
  sigma_pred <- sqrt( sigma_prev^2 + process_noise^2 )
  
  #find k
  k <- sigma_pred^2 / (sigma_pred^2 + obs_noise^2)
  
  #find prediction error between estimated mu and obs
  PE <- obs - mu_pred
  
  #update estimate of state as weighted mean of error and last estimate
  mu_new <- mu_pred + k * PE
  
  #update sigma
  sigma_new <- sqrt( (1-k) * sigma_pred^2 )
  
  #prep output list
  output_list = list(mu = mu_new, sigma = sigma_new, k = k)
  
  return(output_list)
}



```


Test it out
```{r}

x <- seq(0 , 30, by = .5)



mus <- c()
sigmas <- c()
ks <- c()
obs <- c()

#start config
mu = 1
sigma = 1



for (t in x){
  
  #generated noised obs
  noised_observation <- rnorm(n=1,mean = 2, sd =3)
  obs <- c(obs, noised_observation)
  
  
  update <- kalman_update(mu_prev = mu, sigma_prev = sigma, obs_noise = 3, obs=noised_observation, process_noise=0.1)
  
  mu <- update$mu
  sigma <- update$sigma
  K <- update$k
  
  mus <- c(mus, mu)
  sigmas <- c(sigmas, sigma)
  ks <- c(ks, K)
}


plot(x,obs)
points(x, mus, col = "red")

```

Make multivariate kalman filter without motion model
```{r}
mvr_kalman_update <- function(mu_prev_vec, sigma_prev_mat, obs_vec, obs_noise_mat){
  
  #get number of states for matrix construction
  n_dim <- length(mu_prev_vec)
  
  ## Prediction step ## 
  #update mu_pred but assume its constant
  mu_pred_vec <- mu_prev_vec
  
  #update predicted var-covar matrix for state estimate 
  sigma_pred_mat <- sigma_prev_mat
  
  ## Update step ## 
  #Get gain matrix. IE, sigma_prev * (sigma_prev + obs_noise_mat)^{-1}. #maybe add safeguard to matrix-inv
  K_mat = sigma_pred_mat %*% solve(sigma_pred_mat+obs_noise_mat)
  
  #get PE matrix
  PE_vec = obs_vec - mu_pred_vec
  
  #update state vec
  mu_new_vec <- mu_pred_vec + K_mat %*% PE_vec
  
  #Update state var-covariance matrix. (I-K) * sigma_pred. #maybe add numerical safeguard
  sigma_new_mat <- (diag(n_dim) - K_mat) %*% sigma_pred_mat
  
  ## Output ## 
  output_list <- list(mu_vec = mu_new_vec, sigma_mat = sigma_new_mat, K_mat = K_mat )
  return(output_list)
}
```


Make agent function
```{r}

#make a function to construct a list of states/prototypes estimates consisting of a location vec, var_covar matrix and an index
construct_state_list <- function(n_dim, n_prototypes, start_mu, start_sigma){
  
  #prep empty list
  state_list <- vector("list", n_prototypes)

  # make a state for each prototype
  for (i in 1:n_prototypes){
    #make state of correct number of dimensions
    state <- list(mu = rep(start_mu, n_dim), sigma = diag(start_sigma, n_dim), state_index = i, log_p = NULL, choice = NULL)
    
    #store in list
    state_list[[i]] <- state
  } 
  return (state_list)
}



#function for updating all prototypes/state estimates within in a trial. Update this to return choice as well**
update_prototypes <- function(trial_features, trial_feedback, state_list, agent_obs_noise_mat, agent_process_noise_mat){
    
    n_states <- length(state_list)
      
    ## Then loop over all prototypes / states on the trial and update them
    for (j in 1:n_states){
      
      #getvals for current prototype on trial
      mu_vec <- state_list[[j]]$mu
      sigma_mat <- state_list[[j]]$sigma + agent_process_noise_mat #adding drift
      state_type <- state_list[[j]]$state_index
      
      
      ## get prob of choosing prototype
      prototype_sigma <-sigma_mat + agent_obs_noise_mat
      state_list[[j]]$log_p <- dmvnorm(trial_features, mean = mu_vec, sigma = prototype_sigma, log = TRUE)
      
      #if prototype index corresponds to feedback then do a kalman update and update corresponding state/prototype
      if (trial_feedback == state_type){

        
        #do kalman update
        update <- mvr_kalman_update(mu_prev_vec = mu_vec, 
                                    sigma_prev_mat = sigma_mat,
                                    obs_vec = trial_features, 
                                    obs_noise_mat = agent_obs_noise_mat)
      
        #update the state list
        state_list[[j]]$mu <- update$mu_vec
        state_list[[j]]$sigma <- update$sigma_mat
        
        #get k for storage
        K_mat <- update$K_mat
      }
      
      #else just update drifted simga state_list with drift
      else{
        #
        state_list[[j]]$sigma <- sigma_mat
        
      }
    }
  return (state_list)
}

#stable log from course notes:
log_sum_exp <- function(v) {
    m <- max(v)
    m + log(sum(exp(v - m)))
  }

#function from sampling a choice given a state list of prototypes containing log props 
sample_choice <- function(state_list){
  n_states = length(state_list)
  
  log_p_vec <- numeric(n_states)
  #loop over states
  for (i in 1:n_states){
    #get log props
    log_p_vec[i] <- state_list[[i]]$log_p
  }
  
  #get denominator to normalize log_props
  log_denom <- log_sum_exp(log_p_vec)
  
  #make new vec for storing
  p_vec <- numeric(n_states)
  
  #calc normalized propabilities
  for (i in 1:n_states){
    p_vec[i] <- exp(log_p_vec[i] - log_denom)
  }
  
  #sample a choice
  choice <- sample(c(1:n_states), size = 1, prob=p_vec)
  
return(choice)
}


#where:
  #features is list of n_dim vectors. One for each trial
  #feedback is a list of ints describing the state type one for each trial
agent_loop <- function(n_dim, n_prototypes, n_trials, features, feedback, agent_obs_noise, agent_process_noise, start_mu, start_sigma){
  
  ### setup agent ###
  #make agent observation noise matrix (R)
  agent_obs_noise_mat = agent_obs_noise * diag(n_dim)
    
  #make agent process noise matrix (Q)
  agent_process_noise_mat = agent_process_noise * diag(n_dim)
  
  #build a state_list of prototypes. One for each prototype 
  state_list <- construct_state_list(n_dim = n_dim, n_prototypes = n_prototypes, start_mu, start_sigma)
  
  #prep empty list to store state, obs and k for each trial
  results <- vector("list", n_trials)
  
  ### run trials ###
  for (i in 1:n_trials){
    
    ## on trial:
    #get features.     "Should prop check that features and n_dim match"
    trial_features <- features[[i]]
    
    #get feedback, ie what state type was the trial
    trial_feedback <- feedback[i] 
    
    # Then loop over all prototypes / states on the trial and update according to kalman filter if state is the same as observed, 
    # if not just add process noise. Returns list of updated state list and p for each
    state_list <- update_prototypes(trial_features = trial_features,
                                    trial_feedback = trial_feedback,
                                    state_list = state_list,
                                    agent_obs_noise_mat = agent_obs_noise_mat,
                                    agent_process_noise_mat = agent_process_noise_mat)
    
    #make choice given the log props of stimulus being each prototype
    choice <- sample_choice(state_list)
  
    
    #make newlinw

  
  
    #store the state_list and behavoir
    results[[i]] <- list(state_list=state_list, choice=choice)
  }
  #return results
  return(results)
}


```




```{r}

#make feature vec depending on type of index
n_dim = 2
n_prototypes = 2
n_trials = 20
mu_1 = c(2,1)
mu_2 = c(2,1.5)

#index for creating testing vectors
feedback <- rbinom(100, size=1, prob =.5) + 1

#make sigma for mvr_norm
Sigma <- matrix(c(0.5, 0.2, 0.1, 0.3), nrow = 2)


#make features
features <- vector("list", n_trials)
for (i in 1:n_trials){
  if (feedback[i] == 1){
    sample <- mvrnorm(n=1,mu=mu_1, Sigma=Sigma)
  } else{
    sample <- mvrnorm(n=1, mu=mu_2, Sigma=Sigma)
  } 
  features[[i]] <- sample
}


## TEST OUT IF IT STILL TRACKS CORRECT STATES
results <- agent_loop(n_dim=2, 
                      n_prototypes=2,
                      n_trials=n_trials, 
                      features=features, feedback=feedback, agent_obs_noise=0.1, agent_process_noise=0.1, start_mu = .5, start_sigma = 10)

```

```{r}
## COMPLETE CLAUDE TEST## 
##

# Build one df per prototype; rows = trials, cols = mu dimensions
mu_dfs <- lapply(1:n_prototypes, function(j) {
  mu_mat <- do.call(rbind, lapply(1:n_trials, function(i) as.vector(results[[i]]$state_list[[j]]$mu)))
  df <- as_tibble(mu_mat, .name_repair = "minimal")
  colnames(df) <- paste0("dim_", seq_len(n_dim))
  df$trial <- seq_len(n_trials)
  df$prototype <- j
  df
})


obs_df <- do.call(rbind, lapply(1:n_trials, function(i) {
  tibble(dim_1 = features[[i]][1], dim_2 = features[[i]][2], prototype = factor(feedback[i]))
}))

true_mus <- tibble(
  dim_1 = c(mu_1[1], mu_2[1]),
  dim_2 = c(mu_1[2], mu_2[2]),
  prototype = factor(1:2)
)

bind_rows(mu_dfs) %>%
  mutate(prototype = factor(prototype)) %>%
  ggplot(aes(dim_1, dim_2, color = prototype)) +
  geom_path() +
  geom_point(data = obs_df, alpha = 0.3, size = 1.5) +
  geom_point(data = ~filter(.x, trial == 1), shape = 15, size = 3) +
  geom_point(data = ~filter(.x, trial == max(trial)), shape = 17, size = 3) +
  geom_point(data = true_mus, shape = 8, size = 4, stroke = 1.5) +
  labs(x = "Dim 1", y = "Dim 2", color = "Prototype",
       caption = "Points = observations, path = mu trajectory, square = start, triangle = end, star = true mu") +
  theme_minimal()
```
# next step
make an loop that initilizes agents:
  sample qs 
  and rs
  
  run agent for trial
  
and outputs a df of choice behavoir in the format as emperical data.

```{r}
results_df <- tibble(
  trial    = 1:n_trials,
  choice   = sapply(1:n_trials, function(i) results[[i]]$choice),
  feedback = feedback[1:n_trials]
) %>%
  mutate(
    correct             = as.integer(choice == feedback),
    cumulative_accuracy = cumsum(correct) / trial
  )

ggplot(results_df, aes(x = trial, y = cumulative_accuracy)) +
  geom_line() +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "gray50") +
  ylim(0, 1) +
  labs(x = "Trial", y = "Cumulative Accuracy", title = "Cumulative Accuracy Over Trials") +
  theme_minimal()
```


```{r}
#make schedule
n_dim <- 5
n_prototypes <- 2

stimuli_combinations <- do.call(expand_grid, setNames(rep(list(0:1), n_dim), paste0("dim_", 1:n_dim)))

make_stimuli_order <- function(){
  
  num_stimuli = 32
  num_blocks = 3

  blocks <- vector("list", num_blocks)

  for (i in 1:num_blocks){
    stimuli_order <- stimuli_combinations[sample(num_stimuli), ]
    blocks[[i]] <- stimuli_order %>% 
      mutate(block = i, trial_id = 1:num_stimuli)
  }

  ##HAVENT CHECKED RULES THROUGH** 
  bind_rows(blocks) %>%
    mutate(
      danger = case_when(
        block == 1 ~ as.integer(dim_1 == 1 & dim_3 == 1),
        block == 2 ~ as.integer(dim_4 == 1),
        block == 3 ~ as.integer(dim_4 == 1 & dim_5 == 1)
      ),
      nutrition = case_when(
        block == 1 ~ as.integer(dim_4 == 1),
        block == 2 ~ as.integer(dim_1 + dim_2 + dim_3 >= 2),
        block == 3 ~ as.integer(dim_1 + dim_2 + dim_3 + dim_5 >= 2)
      ), 
      #"Responses are 1-4, 
      #where 3 and 4 indicate danger, 
      #1 and 2 not danger; 
      #2 and 4 indicate nutritious,
      #1 and 3 not nutritious"
      feedback = case_when(
        danger == 0 & nutrition == 0 ~ 1,
        danger == 0 & nutrition == 1 ~ 2,
        danger == 1 & nutrition == 0 ~ 3,
        danger == 1 & nutrition == 1 ~ 4
      )
    ) 
}
```

```{r}
#def function to loop over number of agents
sim_agents <- function(n_agents, q_mean, q_sd, r_mean, r_sd, start_mu, start_sigma){

  agent_results <- vector("list", n_agents)

  #loop over agents
  for (i in 1:n_agents){

    #sample vals on log scale directly
    log_q <- rnorm(1, mean = q_mean, sd = q_sd)
    log_r <- rnorm(1, mean = r_mean, sd = r_sd)

    stimuli_df <- make_stimuli_order()

    features <- pmap(stimuli_df %>% dplyr::select(starts_with("dim_")), c)
    feedback  <- stimuli_df$feedback  # remap 0/1 -> 1/2 to match state indices

    results <- agent_loop(n_dim = n_dim,
                          n_prototypes = 4,
                          n_trials = nrow(stimuli_df),
                          features = features,
                          feedback = feedback,
                          agent_obs_noise = exp(log_r),
                          agent_process_noise = exp(log_q),
                          start_mu = start_mu, 
                          start_sigma = start_sigma)

    agent_results[[i]] <- list(agent_id = i, log_q = log_q, log_r = log_r,
                               stimuli_df = stimuli_df, results = results)
  }

  return(agent_results)
}

test_results <- sim_agents(n_agents = 2, q_mean = -2, q_sd = 1, r_mean = 0, r_sd = 1, start_mu =.5, start_sigma = 10)

# cumulative accuracy per agent
accuracy_df <- map_dfr(seq_along(test_results), function(i) {
  agent <- test_results[[i]]
  n_t <- length(agent$results)
  tibble(
    trial    = 1:n_t,
    agent_id = i,
    choice   = sapply(1:n_t, function(t) agent$results[[t]]$choice),
    feedback = agent$stimuli_df$danger + 1
  ) %>%
    mutate(
      block               = ceiling(trial / 32),
      trial_in_block      = ((trial - 1) %% 32) + 1,
      correct             = as.integer(choice == feedback)
    ) %>%
    group_by(block) %>%
    mutate(cumulative_accuracy = cumsum(correct) / trial_in_block) %>%
    ungroup()
})

ggplot(accuracy_df, aes(x = trial_in_block, y = cumulative_accuracy, color = factor(agent_id))) +
  geom_line() +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "gray50") +
  ylim(0, 1) +
  facet_wrap(~block, labeller = label_both) +
  labs(x = "Trial within block", y = "Cumulative Accuracy", color = "Agent") +
  theme_minimal()

# prototype location trajectories (dim_1 vs dim_2)
mu_df <- map_dfr(seq_along(test_results), function(i) {
  agent <- test_results[[i]]
  n_t <- length(agent$results)
  map_dfr(1:2, function(j) {
    map_dfr(1:n_t, function(t) {
      mu <- agent$results[[t]]$state_list[[j]]$mu
      tibble(trial = t, agent_id = i, prototype = j, dim_1 = mu[1], dim_2 = mu[2])
    })
  })
})

# add block to mu_df (32 stimuli per block)
mu_df <- mu_df %>%
  mutate(block = ceiling(trial / 32))

# true prototype means per block (mean feature vector for each category)
true_mus <- map_dfr(1:3, function(b) {
  stimuli_combinations %>%
    mutate(
      prototype = if (b == 1) as.integer(dim_1 == 1 & dim_3 == 1) + 1
                  else if (b == 2) as.integer(dim_4 == 1) + 1
                  else as.integer(dim_4 == 1 & dim_5 == 1) + 1
    ) %>%
    group_by(prototype) %>%
    summarise(dim_1 = mean(dim_1), dim_2 = mean(dim_2), .groups = "drop") %>%
    mutate(block = b)
})

ggplot(mu_df, aes(x = dim_1, y = dim_2, color = factor(prototype),
                  group = interaction(agent_id, prototype))) +
  geom_path() +
  geom_point(data = true_mus, aes(x = dim_1, y = dim_2, color = factor(prototype)),
             shape = 8, size = 4, stroke = 1.5, inherit.aes = FALSE) +
  facet_wrap(~block, labeller = label_both) +
  labs(x = "Dim 1", y = "Dim 2", color = "Prototype",
       caption = "Star = true prototype mean") +
  theme_minimal()

```



```{r}

test_results_100 <- sim_agents(n_agents = 100, q_mean = -2, q_sd = 1, r_mean = 0, r_sd = 1, start_mu =.5, start_sigma = 10)
```

```{r}
accuracy_df_100 <- map_dfr(seq_along(test_results_100), function(i) {
  agent <- test_results_100[[i]]
  n_t <- length(agent$results)
  tibble(
    trial    = 1:n_t,
    agent_id = i,
    choice   = sapply(1:n_t, function(t) agent$results[[t]]$choice),
    feedback = agent$stimuli_df$danger + 1
  ) %>%
    mutate(
      block          = ceiling(trial / 32),
      trial_in_block = ((trial - 1) %% 32) + 1,
      correct        = as.integer(choice == feedback)
    ) %>%
    group_by(block) %>%
    mutate(cumulative_accuracy = cumsum(correct) / trial_in_block) %>%
    ungroup()
})

accuracy_df_100 %>%
  group_by(block, trial_in_block) %>%
  summarise(
    mean_acc = mean(cumulative_accuracy),
    lo       = quantile(cumulative_accuracy, 0.1),
    hi       = quantile(cumulative_accuracy, 0.9),
    .groups  = "drop"
  ) %>%
  ggplot(aes(x = trial_in_block, y = mean_acc)) +
  geom_ribbon(aes(ymin = lo, ymax = hi), alpha = 0.2) +
  geom_line() +
  geom_hline(yintercept = 0.25, linetype = "dashed", color = "gray50") +
  ylim(0, 1) +
  facet_wrap(~block, labeller = label_both) +
  labs(x = "Trial within block", y = "Cumulative Accuracy",
       caption = "Line = mean, ribbon = 80% interval across 100 agents") +
  theme_minimal()
```



